// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYs5jsWptsHz5DK3fZc1EYscef7s52JWg',
    appId: '1:483365822739:web:5cd1c47bc3bbd402713ae6',
    messagingSenderId: '483365822739',
    projectId: 'redooceit-d3385',
    authDomain: 'redooceit-d3385.firebaseapp.com',
    storageBucket: 'redooceit-d3385.appspot.com',
    measurementId: 'G-23T6LYML01',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxxR8xg06hJ2bOc4VLpgplKICKH8BieFM',
    appId: '1:483365822739:android:5e09373a1571b061713ae6',
    messagingSenderId: '483365822739',
    projectId: 'redooceit-d3385',
    storageBucket: 'redooceit-d3385.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqmViOQOhxAJMbkSK7BroKuQMWBL_3zEc',
    appId: '1:483365822739:ios:630e003ec5d85edc713ae6',
    messagingSenderId: '483365822739',
    projectId: 'redooceit-d3385',
    storageBucket: 'redooceit-d3385.appspot.com',
    iosBundleId: 'com.fawazalrasyid.redooceit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqmViOQOhxAJMbkSK7BroKuQMWBL_3zEc',
    appId: '1:483365822739:ios:65c82a03cd60a4c0713ae6',
    messagingSenderId: '483365822739',
    projectId: 'redooceit-d3385',
    storageBucket: 'redooceit-d3385.appspot.com',
    iosBundleId: 'com.fawazalrasyid.redooceit.RunnerTests',
  );
}
