// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu_mdVZqhRdahVntYjhHcWW3Ai0nhpuQA',
    appId: '1:522880057613:web:6e222410f9bcd785a87044',
    messagingSenderId: '522880057613',
    projectId: 'redooceit-abp',
    authDomain: 'redooceit-abp.firebaseapp.com',
    storageBucket: 'redooceit-abp.appspot.com',
    measurementId: 'G-8KLLJ80EGL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQWwqxbq8mx-HybK4Jn5OctfyJ8OSnYnc',
    appId: '1:522880057613:android:fde263e0dbeaace8a87044',
    messagingSenderId: '522880057613',
    projectId: 'redooceit-abp',
    storageBucket: 'redooceit-abp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRwHplWla_fsn901Ug5soOyBNkf9eO210',
    appId: '1:522880057613:ios:f14c3b0c3ae2cffba87044',
    messagingSenderId: '522880057613',
    projectId: 'redooceit-abp',
    storageBucket: 'redooceit-abp.appspot.com',
    iosBundleId: 'com.fawazalrasyid.redooceit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRwHplWla_fsn901Ug5soOyBNkf9eO210',
    appId: '1:522880057613:ios:024db49b96653066a87044',
    messagingSenderId: '522880057613',
    projectId: 'redooceit-abp',
    storageBucket: 'redooceit-abp.appspot.com',
    iosBundleId: 'com.fawazalrasyid.redooceit.RunnerTests',
  );
}
